name: 88 Candy Bars
favicon: null
layout_spectrum: 0.8204199050087482
typography_spectrum: 0.6568178795278072
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.20148864714428782
  lightness: 0.7732970423530787
  saturation: 0.29137554625049233
  rhythmicContrast: 0.3570830130483955
purpose: []
