name: 88 Candy Bars
favicon: null
layout_spectrum: 0.8204199050087482
typography_spectrum: 0.6568178795278072
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b4886d'
    - '#f1fffd'
    - '#262b3e'
    - '#d8bda0'
    - '#6184bc'
  brandStrength: 0.25
  lightness: 0.7732970423530787
  saturation: 0.29137554625049233
  rhythmicContrast: 0.25
purpose: []
